kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nexus
  namespace: nexus
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "./nexus-data"