kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-nexus
  namespace: nexus
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi